### ISSUE TITLE
CRA SSR : ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Mindgames** [CharlesStover/reactn#30]
Running in to this issue on SSR CRA and have not manage to get around it.

```
$ cross-env NODE_ENV=production node ./server/index.js
/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/reactn/index.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("react")):"function"==typeof define&&define.amd?define("reactn",["react"],e):"object"==typeof exports?exports.reactn=e(require("react")):t.reactn=e(t.React)}(window,function(t){return function(t){var e={};function n(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return t[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=t,n.c=e,n.d=function(t,e,r){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:r})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enum

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/reactn/index.js:1:249)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Mindgames** [comment]
Loading it higher up in the hierarchy producing following error 

```
$ cross-env NODE_ENV=production node ./server/index.js
(node:43730) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at Object.<anonymous> (/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/reactn/index.js:1:249)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/Users/mathias/Dropbox/Projects/slight/rettfinans/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
(node:43730) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43730) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.62s.
```

**Comment by CharlesStover** [comment]
Thank you. I will have to address this Sunday or Monday. I think it is the Webpack configuration targeting browsers specifically, as window shouldn't be used in ReactN itself. But I'll look into it to be sure and correct it accordingly.

**Comment by Mindgames** [comment]
@CharlesStover Awesome! can't wait for the fix.

**Comment by Mindgames** [comment]
https://github.com/webpack/webpack/issues/7112#issuecomment-383866094

**Comment by CharlesStover** [comment]
> [webpack/webpack#7112 (comment)](https://github.com/webpack/webpack/issues/7112#issuecomment-383866094)

ReactN does not have any dependencies on the window object. Webpack is building the package for browsers instead of with NodeJS support; the Webpack build process is what is injecting `window` into the code, which otherwise has no reliance on the `window` object. It seems to be a bug when using `umd` as the library target.

I'm testing [this fix](https://github.com/webpack/webpack/issues/6525#issuecomment-417580843), which seems promising so far. I've tried it with global browser window scope and also the global Node scope.

I'll push `0.1.7` right now to address this.

I will mention that `reactn` does not _officially_ support SSR yet, as there are known bugs and limitations. Primarily, neither re-hydration on the client [#9](https://github.com/CharlesStover/reactn/issues/9) nor concurrent rendering [#17](https://github.com/CharlesStover/reactn/issues/17) are supported. As long as you are setting state in the client and using `resetGlobal` between renders, it should be fine.

Full server-side rendering supported is planned. I just don't have enough experience with SSR yet to implement it thoroughly.
